# Configuration for ServerCore - Fabric

# Lets you enable / disable certain features and modify them.
[features]
  per_player_spawns = false
  disable_spawn_chunks = false
  fast_xp_merging = false
  no_chunk_tick = false
  lobotomize_villagers = false
  lobotomized_tick_interval = 20
  autosave_interval_minutes = 5
  xp_merge_radius = 0.5
  item_merge_radius = 0.5

# Stops animals / villagers from breeding if there are too many of the same type nearby.
[entity_limits]
  enabled = false
  villager_count = 24
  villager_range = 64
  animal_count = 32
  animal_range = 64

# Modifies mobcaps, no-chunk-tick and viewdistance depending on the MSPT.
[dynamic]
  enabled = false
  max_tick_distance = 10
  min_tick_distance = 2
  max_view_distance = 10
  min_view_distance = 2
  max_mobcap = 1.0
  min_mobcap = 0.3